"""Fix model snip

Revision ID: 32e36af81c9f
Revises: e1225154d16e
Create Date: 2024-09-23 22:37:50.736963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e36af81c9f'
down_revision: Union[str, None] = 'e1225154d16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('snippets', 'uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_snippets_id', table_name='snippets')
    op.drop_column('snippets', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippets', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_snippets_id', 'snippets', ['id'], unique=False)
    op.alter_column('snippets', 'uuid',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
