"""обавлена связь между User и Snippet

Revision ID: d235d2a66cef
Revises: 32e36af81c9f
Create Date: 2024-09-25 06:49:04.459519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd235d2a66cef'
down_revision: Union[str, None] = '32e36af81c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
